"""Numbered artifacts: plans, prompts, reports, decisions and figures.

Rule (decisions/001): everything a person reads that is *produced* during the project —
a plan, a prompt for a Claude Code session (written by the planner or by Claude Code itself),
a report, a decision record, a figure — is a numbered, append-only file in its series folder:

    <series>/<NNN>_<slug>.<ext>        NNN = 000, 001, ... allocated only by `new_artifact`

* numbers are unique, start at 000 and have no gaps;
* the slug is lowercase letters, digits and `-`;
* Markdown artifacts carry YAML front matter with `id`, `title`, `series`, `created_utc`,
  `author`, `milestone`, `status`, `supersedes`, `superseded_by`;
* a revision is a *new* number with `supersedes: <old id>`; the old file's only permitted edit
  is `status: superseded` and `superseded_by: <new id>`;
* each series has an `INDEX.md` regenerated by the tool (never hand-edited).

Living documents (one file edited in place, versioned by git) are *not* numbered: README,
CLAUDE.md, docs/PHYSICS.md, docs/CLAIMS.md, docs/PREREGISTRATION.md, docs/PAPER_OUTLINE.md,
configs, STATE.json.  Machine records (evidence/*.json, raw hardware counts) keep their UTC stamps
and job ids because they are immutable and referenced by hash.
"""
from __future__ import annotations

import re
import time
from dataclasses import dataclass, field
from pathlib import Path

import yaml

__all__ = ["SERIES", "Artifact", "list_artifacts", "check_artifacts", "new_artifact", "write_index", "slugify",
           "STATUSES"]

SERIES: dict[str, dict] = {
    "plans": {"ext": (".md",), "front_matter": True, "template": "templates/plan.md", "title": "Plans"},
    "prompts": {"ext": (".md",), "front_matter": True, "template": "templates/prompt.md", "title": "Prompts"},
    "reports": {"ext": (".md",), "front_matter": True, "template": "templates/report.md", "title": "Reports"},
    "decisions": {"ext": (".md",), "front_matter": True, "template": "templates/decision.md", "title": "Decisions"},
    "figures": {"ext": (".png", ".pdf", ".svg"), "front_matter": False, "template": None, "title": "Figures"},
    "jobs": {"ext": (".yaml",), "front_matter": False, "yaml": True, "template": None, "title": "Jobs (requests for the Perlmutter worker)"},
}
STATUSES = ("draft", "active", "done", "superseded", "withdrawn")
NAME_RE = re.compile(r"^(\d{3})_([a-z0-9][a-z0-9-]*)(\.[a-z0-9]+)$")
INDEX = "INDEX.md"
KEEP = {INDEX, ".gitkeep"}


@dataclass
class Artifact:
    series: str
    number: int
    slug: str
    path: Path
    meta: dict = field(default_factory=dict)

    @property
    def id(self) -> str:
        return f"{self.series}/{self.number:03d}"


def slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return re.sub(r"-{2,}", "-", s)[:60].strip("-") or "untitled"


def read_front_matter(path: Path) -> tuple[dict, str]:
    text = path.read_text()
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 4)
    if end < 0:
        return {}, text
    meta = yaml.safe_load(text[4:end]) or {}
    return meta, text[end + 5:]


def write_front_matter(path: Path, meta: dict, body: str) -> None:
    fm = yaml.safe_dump(meta, sort_keys=False, allow_unicode=True, width=1000).strip()
    path.write_text(f"---\n{fm}\n---\n{body}")


def list_artifacts(root: str | Path, series: str) -> list[Artifact]:
    d = Path(root) / series
    out = []
    if not d.exists():
        return out
    for p in sorted(d.iterdir()):
        if p.name in KEEP or p.is_dir():
            continue
        m = NAME_RE.match(p.name)
        if not m:
            out.append(Artifact(series, -1, p.name, p))
            continue
        if SERIES[series].get("yaml") and p.suffix == ".yaml":
            meta = yaml.safe_load(p.read_text()) or {}
        else:
            meta = read_front_matter(p)[0] if SERIES[series]["front_matter"] and p.suffix == ".md" else {}
        out.append(Artifact(series, int(m.group(1)), m.group(2), p, meta))
    return out


def check_artifacts(root: str | Path = ".") -> list[str]:
    """Return a list of human-readable problems (empty list = conventions satisfied)."""
    root = Path(root)
    problems: list[str] = []
    for series, spec in SERIES.items():
        arts = list_artifacts(root, series)
        if not (root / series).exists():
            problems.append(f"{series}/: folder missing")
            continue
        nums = []
        for a in arts:
            rel = a.path.relative_to(root)
            if a.number < 0:
                problems.append(f"{rel}: name must match NNN_slug.ext (NNN three digits, slug a-z 0-9 -)")
                continue
            if a.path.suffix not in spec["ext"]:
                problems.append(f"{rel}: extension {a.path.suffix} not allowed in {series}/ ({', '.join(spec['ext'])})")
            nums.append(a.number)
            if spec.get("yaml"):
                from ..jobs import validate_job

                for pr in validate_job(a.meta, expected_id=a.id, root=root):
                    problems.append(f"{rel}: {pr}")
            if spec["front_matter"]:
                m = a.meta
                if not m:
                    problems.append(f"{rel}: missing YAML front matter")
                    continue
                for key in ("id", "title", "series", "created_utc", "author", "status"):
                    if key not in m or m[key] in (None, ""):
                        problems.append(f"{rel}: front matter lacks '{key}'")
                if m.get("id") != a.id:
                    problems.append(f"{rel}: front matter id '{m.get('id')}' != '{a.id}'")
                if m.get("series") not in (None, series):
                    problems.append(f"{rel}: series '{m.get('series')}' != '{series}'")
                if m.get("status") not in STATUSES:
                    problems.append(f"{rel}: status '{m.get('status')}' not in {STATUSES}")
                for key in ("supersedes", "superseded_by"):
                    ref = m.get(key)
                    if ref:
                        target = _resolve(root, ref)
                        if target is None:
                            problems.append(f"{rel}: {key} '{ref}' does not exist")
                if m.get("status") == "superseded" and not m.get("superseded_by"):
                    problems.append(f"{rel}: status superseded but no superseded_by")
        dup = sorted({n for n in nums if nums.count(n) > 1})
        if dup:
            problems.append(f"{series}/: duplicate numbers {dup}")
        if nums and sorted(set(nums)) != list(range(max(nums) + 1)):
            missing = sorted(set(range(max(nums) + 1)) - set(nums))
            problems.append(f"{series}/: gaps in numbering {missing} (numbers are never deleted; withdraw instead)")
        idx = root / series / INDEX
        if not idx.exists():
            problems.append(f"{series}/INDEX.md missing (run scripts/new_artifact.py --reindex)")
        elif idx.read_text() != render_index(root, series):
            problems.append(f"{series}/INDEX.md is stale (run scripts/new_artifact.py --reindex)")
    return problems


def _resolve(root: Path, ref: str) -> Path | None:
    try:
        series, num = ref.split("/")
        n = int(num)
    except ValueError:
        return None
    for a in list_artifacts(root, series) if series in SERIES else []:
        if a.number == n:
            return a.path
    return None


def render_index(root: str | Path, series: str) -> str:
    root = Path(root)
    spec = SERIES[series]
    lines = [f"# {spec['title']} — index", "", "Generated by `scripts/new_artifact.py`; do not edit by hand.", ""]
    arts = [a for a in list_artifacts(root, series) if a.number >= 0]
    if spec.get("yaml"):
        lines += ["| id | title | kind | where | prompt | commit | created (UTC) |", "|---|---|---|---|---|---|---|"]
        for a in arts:
            m = a.meta
            lines.append(f"| [{a.number:03d}]({a.path.name}) | {m.get('title', '')} | {m.get('kind', '')} | {m.get('where', '')} "
                         f"| {m.get('prompt') or ''} | {str(m.get('commit', ''))[:8]} | {m.get('created_utc', '')} |")
    elif spec["front_matter"]:
        lines += ["| id | title | status | milestone | author | created (UTC) | supersedes |", "|---|---|---|---|---|---|---|"]
        for a in arts:
            m = a.meta
            lines.append(f"| [{a.number:03d}]({a.path.name}) | {m.get('title', '')} | {m.get('status', '')} | {m.get('milestone') or ''} "
                         f"| {m.get('author', '')} | {m.get('created_utc', '')} | {m.get('supersedes') or ''} |")
    else:
        lines += ["| id | file |", "|---|---|"]
        for a in arts:
            lines.append(f"| {a.number:03d} | [{a.path.name}]({a.path.name}) |")
    if not arts:
        lines.append("_(empty)_")
    return "\n".join(lines) + "\n"


def write_index(root: str | Path, series: str) -> Path:
    p = Path(root) / series / INDEX
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(render_index(root, series))
    return p


def next_number(root: str | Path, series: str) -> int:
    nums = [a.number for a in list_artifacts(root, series) if a.number >= 0]
    return max(nums) + 1 if nums else 0


def new_artifact(root: str | Path, series: str, title: str, author: str = "claude-code", milestone: str | None = None,
                 supersedes: str | None = None, ext: str | None = None, body: str | None = None,
                 status: str = "draft", data: dict | None = None) -> Path:
    """Allocate the next number in `series`, create the file from the series template, refresh INDEX.md.

    For figures the file is not created (the caller saves the image to the returned path).
    `supersedes` is an id like 'prompts/004'; the old artifact is marked superseded.
    """
    root = Path(root)
    if series not in SERIES:
        raise ValueError(f"unknown series {series}; choose from {list(SERIES)}")
    spec = SERIES[series]
    ext = ext or spec["ext"][0]
    if ext not in spec["ext"]:
        raise ValueError(f"extension {ext} not allowed in {series}")
    n = next_number(root, series)
    path = root / series / f"{n:03d}_{slugify(title)}{ext}"
    path.parent.mkdir(parents=True, exist_ok=True)
    if spec.get("yaml"):
        doc = {"id": f"{series}/{n:03d}", "title": title, "author": author,
               "created_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}
        doc.update(data or {})
        path.write_text(yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=1000))
    if spec["front_matter"]:
        if supersedes and _resolve(root, supersedes) is None:
            raise ValueError(f"supersedes {supersedes}: no such artifact")
        meta = {"id": f"{series}/{n:03d}", "title": title, "series": series,
                "created_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()), "author": author,
                "milestone": milestone, "status": status, "supersedes": supersedes, "superseded_by": None}
        if body is None:
            tpl = root / spec["template"] if spec["template"] else None
            body = tpl.read_text() if tpl and tpl.exists() else f"\n# {title}\n"
            body = body.replace("{{title}}", title).replace("{{id}}", meta["id"]).replace("{{milestone}}", milestone or "")
        write_front_matter(path, meta, body if body.startswith("\n") else "\n" + body)
        if supersedes:
            old = _resolve(root, supersedes)
            om, ob = read_front_matter(old)
            om["status"] = "superseded"
            om["superseded_by"] = meta["id"]
            write_front_matter(old, om, ob)
            write_index(root, supersedes.split("/")[0])
    write_index(root, series)
    return path
